### PR TITLE
Resolve Issue #1218 #1167

### LINKED ISSUE #1167: Cannot pass boolean values via inputParameters
**Description:**

This is true for infra, deploy, and test configs. If one was specified, which is a common user mistake, following error is thrown:

```
[09:37:24,782] Unhandled error occurred hile running deployment for deployment pattern 'org.wso2.testgrid.common.config.DeploymentConfig@7c2312fa' in TestPlan org.wso2.testgrid.core.exception.TestPlanExecutorException: Error occurred while writing deployment outputs.

	at org.wso2.testgrid.core.TestPlanExecutor.persistAdditionalInputs(TestPlanExecutor.java:678)

	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:512)

	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:144)

	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:275)

	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:138)

	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:130)

	at org.wso2.testgrid.core.Main.main(Main.java:47)

Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String

	at java.util.Properties.store0(Properties.java:834)

	at java.util.Properties.store(Properties.java:818)

	at org.wso2.testgrid.core.TestPlanExecutor.persistAdditionalInputs(TestPlanExecutor.java:676)

	... 6 more

```

```
[m[31m[09:41:43,066] Unhandled error occurred hile running deployment for deployment pattern 'org.wso2.testgrid.common.config.DeploymentConfig@7c2312fa' in TestPlan org.wso2.testgrid.core.exception.TestPlanExecutorException: Error occurred while writing deployment outputs.
	at org.wso2.testgrid.core.TestPlanExecutor.persistAdditionalInputs(TestPlanExecutor.java:678)
	at org.wso2.testgrid.core.TestPlanExecutor.createDeployment(TestPlanExecutor.java:512)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:144)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:275)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:138)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:130)
	at org.wso2.testgrid.core.Main.main(Main.java:47)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at java.util.Properties.store0(Properties.java:834)
	at java.util.Properties.store(Properties.java:818)
	at org.wso2.testgrid.core.TestPlanExecutor.persistAdditionalInputs(TestPlanExecutor.java:676)
	... 6 more
```

https://github.com/wso2/testgrid-job-configs/blob/2761f001c34b6ea216c9bf99c942cb9904515bcd/team-tg/kasung-test.yaml#L42

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### LINKED ISSUE #1218: Colon in URLs passed as input params are escaped
**Description:**

```yaml
RCLocation: "https://product-dist.ballerina.io/nightly/0.992.0-m2-SNAPSHOT/ballerina-0.992.0-m2-SNAPSHOT.zip"
```
This URL becomes when passed in to infrastructure.properties file.
"https\://product-dist.ballerina.io/nightly/0.992.0-m2-SNAPSHOT/ballerina-0.992.0-m2-SNAPSHOT.zip"

### PR DESCRIPTION
**Pull request by ranikamadurawe**
**Purpose**

This PR intends to resolves #1218 and resolves #1167.

### CODE REVIEW

File: common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java [hunk 1]
```diff
@@ -127,7 +126,7 @@ public void setTestType(String testType) {
         this.testType = testType;
     }
 
-    private Map<String, String> inputParameters = new HashMap<>();
+    private HashMap inputParameters = new HashMap<>();
```
Comment (kasunbg) [inline common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java]: Shall we change the type to Map<String, Object> ?

`private Map<String, Object> inputParameters = new HashMap<>();`

File: common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java [hunk 2]
```diff
@@ -163,7 +162,7 @@ public void setRemoteBranch(String remoteBranch) {
      *
      * @return List of inputParameters
      */
-    public Map<String, String> getInputParameters() {
+    public HashMap getInputParameters() {
```
Comment (kasunbg) [inline common/src/main/java/org/wso2/testgrid/common/config/ScenarioConfig.java]: Using HashMap is an internal detail of this class. So, we should not expose that to outside of this class. So, I suggest we use the return type as Map. May be with generic types as Map<String, Object>.

File: common/src/main/java/org/wso2/testgrid/common/config/Script.java [hunk 3]
```diff
@@ -39,7 +39,7 @@
     private Phase phase;
     private String description;
     private String file;
-    private Properties inputParameters = new Properties();
+    private HashMap<String, Object> inputParameters = new HashMap<>();
```
Comment (kasunbg) [inline common/src/main/java/org/wso2/testgrid/common/config/Script.java]: Same as above.
