### PR TITLE
Fix redirection to requested URLs after completion of login.

### LINKED ISSUE #772: [Dashboard] Direct links redirect to homepage for non-logged user
**Description:**
A logged in user can go for a direct link. But for a non-logged user, he will need to enter the link at the homepage after logged it. The better way is to go to the direct link page at first time.

**Suggested Labels:**
Bug

**Affected Product Version:**
m28
**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**
Try direct link from a 'fresh' browser.

### PR DESCRIPTION
**Pull request by pasindujw**
**Purpose**
A logged in user can go for a direct link. But for a non-logged user, he will need to enter the link at the homepage after logged it. The better way is to go to the direct link page at first time.
Fixes #772 

**Goals**
Increase user experience.

**Approach**
Keep the request URI as a relay-state when passing the SAML request to Identity Provider and receive back it after the completion of login.

**User stories**
As a non-logged user, I should be able to use direct link and see the relevant page (after the intermediate step of signing-in).

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
 
**Learning**
https://docs.wso2.com/display/IS530/SAML+2.0+Web+SSO
https://medium.com/@pasindujay/web-sso-for-react-servlet-application-with-wso2-identity-server-f1a49b083589

### CODE REVIEW

File: web/src/main/java/org/wso2/testgrid/web/api/SSOService.java [hunk 1]
```diff
@@ -81,9 +83,14 @@ public Response createSession(@FormParam("SAMLResponse") String responseMessage)
         try {
             validateSignature(saml2Response.getSignature());
             request.getSession();
+            String redirectUri;
+            if (StringUtil.isStringNullOrEmpty(relayState)) {
+                redirectUri = Constants.WEBAPP_CONTEXT;
+            } else {
+                redirectUri = relayState;
+            }
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/SSOService.java]: In summary, this is actually:
redirectUri = StringUtil.isStringNullOrEmpty(relayState) ? Constants.WEBAPP_CONTEXT : relayState;
:)

File: web/src/main/java/org/wso2/testgrid/web/api/SSOService.java [hunk 2]
```diff
@@ -65,7 +66,8 @@
       * @return Redirection to dashboard home page.
```
Comment (lasanthaDLPDS) [inline web/src/main/java/org/wso2/testgrid/web/api/SSOService.java]: Since this is now redirected to requesting page, shall we update the comment as well?
