### PR TITLE
Fix lengthy and duplicate names generated for infrastructure provisioning scripts

### LINKED ISSUE #599: CF testplan execution fails due to exceeding length of script name
**Description:**
The name generated for CF script exceeds 120 characters and the testplan execution fails with the following error.

```
[m[32m[09:19:56,396] Creating CloudFormation Stack 'infra-for-two-node-deployment-VDZ7LA-8DVPQ7-B6VROH-8WJTBY-BJ5D1V-X8HMA6-IK0KJR-3TRTGX-0UNA29-0G6C3N-7J597K-W87CEL-MRAYEI-H41ONX-GZ24A3-IP5M2U-7V7TAA-YVF984-XLDX6C-IZJBWZ-K5XIZK-9TRCRA-JYQZPE-AYPYMR-A6VM93-L182I9-4GWP8G-679ANJ-67HRIT-VVHFEU-6PZUI8-H4G417-OALKIP-WC5FVA-57K5F8-YLNW09-G0679Z-E9WRPD-Y863OE-HUPUBE-AF0IP3-94RA4M-BX8FEL-WCC16Z-1MIGV1-ZWVING-WGJXVA-JONI0L' in region 'null'. Script : pattern-1-with-puppet-cloudformation.template.yml
[m[31m[09:19:57,145] Unknown exception while provisioning the infrastructure: Stack name cannot exceed 128 characters (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 082814ab-2c20-11e8-8c54-49ba50c9cc8f) com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Stack name cannot exceed 128 characters (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 082814ab-2c20-11e8-8c54-49ba50c9cc8f)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:2607)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:2583)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.executeCreateStack(AmazonCloudFormationClient.java:542)
	at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.createStack(AmazonCloudFormationClient.java:519)
	at org.wso2.testgrid.infrastructure.providers.AWSProvider.doProvision(AWSProvider.java:189)
	at org.wso2.testgrid.infrastructure.providers.AWSProvider.provision(AWSProvider.java:132)
	at org.wso2.testgrid.core.TestPlanExecutor.provisionInfrastructure(TestPlanExecutor.java:199)
	at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:81)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:222)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:118)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:124)
	at org.wso2.testgrid.core.Main.main(Main.java:47)

```

This is due to a bug in the name generation which gets longer with the number of infrastructure combinations.

**Suggested Labels:**
Type/Bug, Severity/Blocker, Priority/Highest

**Suggested Assignees:**
AsmaJ

**Related Issues:**
#582 - Occurs due to the same bug

### PR DESCRIPTION
**Pull request by azinneera**
**Purpose**
Fixes the bug in generation of the unique name for infrastructure provisioning script.
Resolves #599 and #582 

**Goals**
Resolve the bug in unique name generation for infrastructure provisioning script

**Approach**
Introduce clone() to Provisioner and Script.

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: common/src/main/java/org/wso2/testgrid/common/config/Script.java [hunk 1]
```diff
@@ -141,4 +143,14 @@ public String toString() {
             return this.name;
         }
     }
+
+    @Override
+    public Script clone() {
+
```
Comment (harshanL) [inline common/src/main/java/org/wso2/testgrid/common/config/Script.java]: Remove the unnecessary line break.

Comment (azinneera) [reply common/src/main/java/org/wso2/testgrid/common/config/Script.java]: Fixed in 5c9f246
