### PR TITLE
TESTGRID_HOME should default to ~/.testgrid if the env variable is not found

### LINKED ISSUE #393: TESTGRID_HOME should default to ~/.testgrid if the env variable is not set.
**Description:**
We shouldn't just fail if the TESTGRID_HOME env var is not found. Instead, we should default to an appropriate location such as ~/.testgrid.

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
0.9.0-m9
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by kasunbg**
## Purpose
We shouldn't just fail if the TESTGRID_HOME env var is not found. Instead, we should default to an appropriate location such as ~/.testgrid.

Resolves #393

## Goals
Better user experience

## Approach
Defaults to ~/.testgrid

## User stories
N/A

## Release note
N/A

## Documentation
Default testgrid_home is set to ~/.testgrid.

## Training
N/A

## Certification
N/A

## Marketing
N/A
## Automation tests
N/A
## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java [hunk 1]
```diff
@@ -158,7 +160,14 @@ public static String executeCommand(String command, File workingDirectory, Deplo
      */
     public static String getTestGridHomePath() {
         String testGridHome = EnvironmentUtil.getSystemVariableValue(TESTGRID_HOME_ENV);
-        Path testGridHomePath = Paths.get(testGridHome);
+        Path testGridHomePath;
+        if (testGridHome == null) {
+            logger.warn("TESTGRID_HOME environment variable not set. Defaulting to ~/.testgrid.");
+            testGridHomePath = DEFAULT_TESTGRID_HOME;
```
Comment (vidurananayakkara) [inline common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java]: What if the default directory is not available. IMO we should create a directory if not exists. WDYT?

File: common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java [hunk 2]
```diff
@@ -158,7 +160,14 @@ public static String executeCommand(String command, File workingDirectory, Deplo
      */
     public static String getTestGridHomePath() {
         String testGridHome = EnvironmentUtil.getSystemVariableValue(TESTGRID_HOME_ENV);
-        Path testGridHomePath = Paths.get(testGridHome);
+        Path testGridHomePath;
+        if (testGridHome == null) {
```
Comment (yasassri) [inline common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java]: Since we are doing a null check here, IMO we don't need to null-check the path again in Main#49.

File: common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java (hunk 1 above)
Comment (kasunbg) [reply common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java]: Then, it will get created via https://github.com/wso2/testgrid/blob/master/core/src/main/java/org/wso2/testgrid/core/command/GenerateTestPlanCommand.java#L298

But, it makes sense to create the directory here itself. Added!

File: common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java (hunk 2 above)
Comment (kasunbg) [reply common/src/main/java/org/wso2/testgrid/common/util/TestGridUtil.java]: Done..
