### PR TITLE
Use stack ID instead of stack name for describing stacks

### LINKED ISSUE #469: DescribeStacksRequest should use the CloudFormation stackId instead of its name.
**Description:**
Using the stackId is the only guaranteed way to make sure we get the stack that actually belong to this particular test-run.                                                                                                                                               

**Affected Product Version:**
 0.9.0-m12                                                                                                                      

**OS, DB, other environment details and versions:**
  N/A                                                                                                      
**Steps to reproduce:**
  See above                                                                                                                                     
**Related Issues:**
 N/A

### PR DESCRIPTION
**Pull request by kasunbg**
## Purpose
Use stack ID instead of stack name for describing stacks.
Fixes #469.

## Goals
Using the stackId is the only guaranteed way to make sure we get the stack that actually belong to this particular test-run.

### CODE REVIEW

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java [hunk 1]
```diff
@@ -132,7 +136,7 @@ public Deployment createInfrastructure(Script script, String infraRepoDir) throw
             logger.info(StringUtil.concatStrings("Stack : ", cloudFormationName, " creation completed !"));
```
Comment (pasindujw) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java]: Do we need to use stack.getStackId() here in the log?
