### PR TITLE
Resolve issue #1249

### LINKED ISSUE #1249: NPE when test.sh location is not specified in tg yaml
**Description:**
Following error was noticed for the scenarioConfig specified below.

```java
Exception in thread "main" java.lang.NullPointerException 
at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:273) 
at java.nio.file.Paths.get(Paths.java:84) 
at org.wso2.testgrid.core.phase.TestPhase.runScenarioTests(TestPhase.java:149) 
at org.wso2.testgrid.core.phase.TestPhase.executePhase(TestPhase.java:101) 
at org.wso2.testgrid.core.phase.Phase.execute(Phase.java:61) 
at org.wso2.testgrid.core.TestPlanExecutor.execute(TestPlanExecutor.java:83) 
at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:279) 
at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:133) 
at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:130) 
at org.wso2.testgrid.core.Main.main(Main.java:47)
```

```yaml
scenarioConfigs:
  - testType: TESTNG
    remoteRepository: "https://github.com/RidmiR/micro-integrator"
    name: "ref-scenario"
    description: "Test-Phase-1"
#    file: scenarioTestsRepository/ref-scenario/tests/test.sh
```

### PR DESCRIPTION
**Pull request by udhanMti**
This PR resolves #1249 - NPE when test.sh location is not specified in tg yaml

### CODE REVIEW

File: core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java [hunk 1]
```diff
@@ -146,22 +146,23 @@ private void runScenarioTests()
...
-                        scenarioConfig.getFile());
-                if (scenarioDir !=  null) {
-                    Path parent = scenarioDir.getParent();
-                    Path file = scenarioDir.getFileName();
-                    if (parent == null) {
-                        parent = Paths.get("");
-                    }
-                    if (file == null) {
-                        file = Paths.get("test.sh");
+                if (scenarioConfig.getFile() != null) {
```
Comment (kasunbg) [inline core/src/main/java/org/wso2/testgrid/core/phase/TestPhase.java]: If we can detect the non-existence of the file and then gracefully log that and exit, that would provide better user experience for the end-user. I don't think we should hide the error message, because this is an actual user error.
