### PR TITLE
Print a summary of the execution at the end of run-testplan

### LINKED ISSUE #517: Print a summary of the execution at the end of run-testplan
**Description:**
$subject similar to how Maven works. In our case, we have three static steps for which we can show a summary:

```log
------------------------------------------------------------------------
SUMMARY

Infrastructure Provisioner  ...........  SUCCESS [  14.491 m]
Deployment Creation    ................  SUCCESS [ 30.198 m]
Scenario Execution    ..................  SUCCESS [  5.306 m]
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 44.762 s
Finished at: 2018-02-22T19:51:16+01:00
Final Memory: 117M/850M
------------------------------------------------------------------------
```

**Affected Product Version:**
0.9.0-m16

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by kasunbg**
**Purpose**
Print a summary of the execution at the end of run-testplan

Fixes #517 

**Goals**
Better readability of the log.

**Approach**
similar to maven

```
[19:40:15,550] There are test failures...
[19:40:15,550] Failed tests:
[19:40:15,555]   Sample scenario 02::Sample Testcase 02: fail
[19:40:15,555]   Sample scenario 02::Sample Testcase 03: fail
[19:40:15,555] 
[19:40:15,555] Tests run: 3, Failures/Errors: 2
[19:40:15,555] 
[19:40:15,558] ------------------------------------------------------------------------
[19:40:15,560] Test Plan Summary for {DBEngine: "mysql"}
[19:40:15,560] Sample scenario 01 ................................. SUCCESS
[19:40:15,560] Sample scenario 02 ................................. FAIL
[19:40:15,560] ------------------------------------------------------------------------
[19:40:15,560] TEST RUN FAIL
[19:40:15,561] ------------------------------------------------------------------------
[19:40:15,561] Total Time: 34 days 7 hours
[19:40:15,561] Finished at: Thu Jun 07 19:40:15 IST 2018
[19:40:15,561] ------------------------------------------------------------------------
```

**Automation tests**
Yes.

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java [hunk 1]
```diff
@@ -52,7 +56,9 @@
  */
 public class TestPlanExecutor {
 
+    public static final int LINE_LENGTH = 72;
     private static final Logger logger = LoggerFactory.getLogger(TestPlanExecutor.class);
+    private static final int MAX_NAME_LENGTH = 52;
```
Comment (pasindujw) [inline core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java]: Any reasons to use these numbers for lengths? ( TMK :) )

Comment (kasunbg) [reply core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java]: Only requirement was to keep the scenario pass/fail status lines within the LINE_LENGTH (72) character limit. 20 characters were reserved to print things like '[INFO]' and 'SUCCESS/FAIL'... :)
