### PR TITLE
Persist TestPlan to database at generate-TestPlan step

### LINKED ISSUE #514: GenerateTestPlanCommand should set the PENDING state in database
**Description:**
Right now, our UI only works in the happy path. Whenever a build gets broken for some issue in testgrid or in repo scripts, the UI goes haywire. It even fails to let you download the log file.

Therefore, we need to set the PENDING state into the database before attempting to do the actual task. After the task completion, if an exception is thrown, then we need to set FAILED state into the database.

**Affected Product Version:**
0.9.0-m14

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by harshanL**
**Purpose**
To persist testplan at the generate-test-plans step instead of run-testplan step. This will also resolve #514 and #431.

**Goals**
TestGrid should persist test-plan information to DB at the generate-testplan step. 

**Approach**
Persisted testplan to the database when executing generate-testplan command and saved the testplan.yaml with the testplan-id. When running run-test-plan command, it will fetch the appropriate testplan object from database using the id.

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

**Related Issues**
#431, #552

### CODE REVIEW

File: core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java [hunk 1]
```diff
@@ -79,6 +91,14 @@ public void init() throws Exception {
         int random = new Random().nextInt(100);
         product.setName("wso2-" + random);
 
+        this.testPlan = new TestPlan();
+        testPlan.setId("abc");
```
Comment (kasunbg) [inline core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java]: Shall we use consistent Test plan IDs? I see that we used TP_1 in the other test case.

Comment (harshanL) [reply core/src/test/java/org/wso2/testgrid/core/command/GenerateTestPlanCommandTest.java]: @kasunbg : Haven't add a constant since it has not been used more than once. Do we need to?
