### PR TITLE
Pre-processing step to CloudFormation Scripts

### LINKED ISSUE #487: Error when creating multiple AWS stacks which uses same IS CF template.
**Description:**
Occurred with cloudformation-IS script [1]. When trying to create a second stack which uses the same template the task stopped with saying,
load-balancer "identity-demo" already exists (Not the exact words saw in error).
Once modified the second stack's template's load-balancer name, the error was gone.

But it should be possible to run multiple stacks without manually editing the template.

**Suggested Labels:**
Type/Bug 

**Affected Product Version:**
TestGrid-v0.90-m12-Snapshot

**OS, DB, other environment details and versions:**    
Included in the CF script.

**Steps to reproduce:**
Log into AWS. Go to Stacks dashboard. Create two stacks with same CF script in [1].

[1] - https://github.com/wso2/cloudformation-is/blob/master/cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml

### PR DESCRIPTION
**Pull request by pasindujw**
Introducing the pre-processing step to do that modification and leaving option to do any other modifications which might come in future.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied. See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.wso2.testgrid.infrastructure;
+
+import org.wso2.testgrid.common.util.StringUtil;
+
```
Comment (lahirus) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: Can avoid the new line?

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java [hunk 2]
```diff
@@ -105,10 +106,11 @@ public Deployment createInfrastructure(Script script, String infraRepoDir) throw
 
         CreateStackRequest stackRequest = new CreateStackRequest();
         stackRequest.setStackName(cloudFormationName);
+        CloudFormationScriptPreprocessor cfScriptPreprocessor = new CloudFormationScriptPreprocessor();
```
Comment (kasunbg) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java]: Can we create an instance variable for this?

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+        StringBuilder newScript = new StringBuilder();
+        Pattern pattern = Pattern.compile("\\b(" + key + ":)");
+        //Take each line and check for the reg-ex pattern.
+        for (String line : script.split("\\r?\\n")) {
+            if (pattern.matcher(line).find()) {
+                String value = line.split(":")[1];
+                String newValue = value + StringUtil.generateRandomString(RANDOMIZED_STR_LENGTH);
+                line = line.split(":")[0] + ":" + newValue;
+            }
+            newScript.append(line).append(System.lineSeparator());
```
Comment (kasunbg) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: I think we can improve the regex matching logic. I created a sample regex: https://regexr.com/3l1pf. Please check. This was not tested for edge cases.

Comment (pasindujw) [reply infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: Yes. Checked with existing IS CF scripts and working as expected.

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java (hunk 2 above)
Comment (pasindujw) [reply infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java]: +1. Will move declaring to class level and initializing to constructor so that `createInfrastructure` will be using single processor object.

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java (hunk 1 above)
Comment (pasindujw) [reply infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: Hi Lahiru, This new line is due to IDE configuration where it adds a new line between  (java.___ , javax.__ imports ) and (other imports). 
AFAIK WSO2 uses the configuration. :)

te

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java (hunk 3 above)
Comment (pasindujw) [reply infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: Used the above reg-ex with adding one more middle bracket to make 3 groups.
 `(\\s+)(" + key + ")\\s*:\\s*(.*)`
