### PR TITLE
Fix dashboard URLs direct accessing issue and Modified URL patterns 

### LINKED ISSUE #425: Dashboard direct access to dashboard/testplans/ URL does not work
**Description:**
We need to support direct url access to testplans and testplan history. Currently, direct URLs lead to an empty page.

image

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Access below URL in a incognito window:
https://testgrid-live-dev.private.wso2.com/testgrid/dashboard/testplans/ca29d91d-38d2-42cc-b3bb-03839d20bdda#scenario29

2. Check the errors in the browser console.

**Related Issues:**
N/A

### LINKED ISSUE #730: Dashboard direct accessing failed when the user isn't logged in
**Description:**

This issue is related to #425, In the #425, the request is reached to the page but page rendering has the issue. In this case, when the user requesting the page it should be redirected to the login page, but it doesn't redirect to the login page.

**Affected Product Version:**
testgrid-:0.9.0-m23

**OS, DB, other environment details and versions:**    
OS - Ubuntu
DB - MySQL

**Steps to reproduce:**

- Enable SSO
- Setup WSO2 IS with TESTGRID
- Access the deploymnet pattern displaying page directly on the browser incognito window
- The request should be redirect to login page but It throws errors.

**Related Issues:**
#425

### LINKED ISSUE #731: Modify Testgrid dashboard URLs
**Description:**

In order to increase human readability of URLs modify TESTGRID dashboard URL patterns as following way.

- Homepage / Job listing page
    - `https://<host>:<port>/`
- Results of deployment patterns for a specific product displaying Page
    - `https://<host>:<port>/ <product-name>` 
- All result for a specific infra combination displaying page
    - `https://<host>:<port>/<product-name>/<deployment-pattern-name>/<testplan-id>/infra`
- Test result displaying and live log displaying page
    - `https://<host>:<port>/<product-ame>/<deployment-pattern-name>/test-plans/<testplan-id>`

**Related Issues:**
#425

### PR DESCRIPTION
**Pull request by lasanthaDLPDS**
**Purpose**

The purpose of this PR is to fix TESTGRID dashboard URLs direct accessing issue. This resolves #425, resolves #731, resolves #730

**Goals**

In order to fix TESTGRID dashboard URLs direct accessing issue, check the existing of properties at the page loading time. If those are not available invoke d backend API and get required data to render pages. Further added bootstrap styling for pages and fixed issues which are related to displaying info on infra combination page and fixed formatting issues as well.

**Approach**

1t
2t
3t

**User stories**

N/A

**Release note**

N/A

**Documentation**
N/A

**Training**
N/A

**Certification**
N/A

**Marketing**
N/A

**Automation tests**
 - Unit tests 
    N/A
 - Integration tests
    N/A

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

**Samples**
N/A

**Related PRs**
N/A

**Migrations (if applicable)**
N/A

**Test environment**
JDK - 1.8
OS - Ubuntu
DB - MySQL
Browser - Chrome
 
**Learning**
N/A

### CODE REVIEW

File: web/src/main/java/org/wso2/testgrid/web/api/ProductService.java [hunk 1]
```diff
@@ -122,11 +122,11 @@ public Response getAllProductStatuses() {
         try {
             for (Product product : productUOW.getProducts()) {
                 ProductStatus status = new ProductStatus();
-                status.setId(product.getId());
-                status.setName(StringUtil.concatStrings(product.getName()));
+                status.setProductId(product.getId());
+                status.setProductName(StringUtil.concatStrings(product.getName()));
```
Comment (harshanL) [inline web/src/main/java/org/wso2/testgrid/web/api/ProductService.java]: I think we don't need to use StringUtil.concatStrings here.

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 2]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
+                                backgroundColor: "#cdffba"
+                            }}>
+                                <Table responsive>
+                                    <tbody>
+                                    <tr>
+                                        <td style={{padding: 5}}>
+                                            <img
+                                                src={require('../success.png')}
+                                                style={{
+                                                    verticalAlign: "middle",
```
Comment (azinneera) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: Shall we specify classes for these elements and write the styles in a separate css file? That way we will not need to duplicate the styles. We can do it as a separate effort btw.

Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: +1 yes, we have to move this type of repeating styling into a separate CSS file. This fix resolves formatting issues and +1 for addressing this in a separate effort. Further, IMO we can use icons instead of these images. WDYT

File: web/src/main/java/org/wso2/testgrid/web/api/ProductService.java [hunk 3]
```diff
@@ -138,6 +138,44 @@ public Response getAllProductStatuses() {
...
+            if (productInstance.isPresent()) {
+                product = productInstance.get();
+                productStatus.setProductId(product.getId());
+                productStatus.setProductName(product.getName());
+                productStatus.setLastfailed(APIUtil.getTestPlanBean(testPlanUOW.getLastFailure(product), false));
+                productStatus.setLastBuild(APIUtil.getTestPlanBean(testPlanUOW.getLastBuild(product), false));
+                productStatus.setProductStatus(testPlanUOW.getCurrentStatus(product).toString());
+            } else {
+                String msg = "Could not found a product for requested product name in the TestGrid.";
+                logger.error(msg);
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/ProductService.java]: How meaningful is this error log? Shall we improve the log message?

File: web/src/main/java/org/wso2/testgrid/web/api/ProductService.java [hunk 4]
```diff
@@ -138,6 +138,44 @@ public Response getAllProductStatuses() {
...
+                return Response.status(Response.Status.NOT_FOUND).entity(msg).build();
+            }
+            return Response.status(Response.Status.OK).entity(productStatus).build();
+        } catch (TestGridDAOException e) {
+            String msg = "Error occurred while fetching the Product statuses ";
+            logger.error(msg, e);
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/ProductService.java]: Same as above. When running multiple products a production system, this error log won't provide enough data to debug an issue.

File: web/src/main/react-dashboard/src/components/ProductStatusView.js [hunk 5]
```diff
@@ -96,90 +96,93 @@ class ProductStatusView extends Component {
...
+                            );
+                        } else {
+                            return ("No failed builds yet!")
+                        }
+                    })()}
+                </td>
+                <td> <img src={require('../play.png')} width="36" height="36" data-tip="Execute job" onClick={() =>
+                { window.location = '/job/'+ product.productName +'/build' }} /> <ReactTooltip /></td>
+                <td ><img src={require('../configure.png')} width="36" height="36" onClick={() => { window.location =
+                    '/job/'+ product.productName +'/configure' }} data-tip="Configure job" style={{ cursor: 'pointer' }}/>
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/ProductStatusView.js]: Is this URL correct? The /job/job-name/configure is coming from Jenkins webapp.

File: web/src/main/react-dashboard/src/components/ProductStatusView.js [hunk 6]
```diff
@@ -96,90 +96,93 @@ class ProductStatusView extends Component {
...
+                    <ModalFooter>
+                        <Button color="danger" onClick={()=>this.toggle("")}>OK</Button>{' '}
+                    </ModalFooter>
+                </Modal>
+            </div>
+        )
+    }
 }
 
 export default ProductStatusView;
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/ProductStatusView.js]: Missing new line. Not your code though. :)

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 7]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
-      inputStreamSize: "",
-      showLogDownloadErrorDialog: false
-    };
-  }
+    constructor(props) {
+        super(props);
+        this.state = {
+            testScenarioSummaries: [],
+            scenarioTestCaseEntries: [],
+            testSummaryLoadStatus: PENDING,
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: PENDING status means that the test is still running. Does it make sense to change the default status to DID_NOT_RUN which shows a gray-colored icon? When the actual data comes, we can populate with correct properties. wdyt?

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 8]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
-  componentDidMount() {
-    const testScenarioSummaryUrl = TESTGRID_CONTEXT + '/api/test-plans/test-summary/' +
-      this.props.active.reducer.currentInfra.testPlanId;
-    const logTruncatedContentUrl = TESTGRID_CONTEXT + '/api/test-plans/log/' +
-      this.props.active.reducer.currentInfra.testPlanId + "?truncate=" + true;
+    componentDidMount() {
+        let currentInfra = {};
+        let currentUrl = window.location.href.split("/");
+        currentInfra.relatedProduct = currentUrl[currentUrl.length - 4];
+        currentInfra.relatedDeplymentPattern = currentUrl[currentUrl.length - 3];
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: L63-L64 code logic is vulnerable for any change in URL contexts. It may fail silently. Is there a better way to handle this? Probably we can use some kind of regex or something similar to jax-rs @Path annotation value.

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 9]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
+        this.setState({ logContent: this.state.logContent + data });
+    }
 
-  handleError(response) {
-      if (response.status.toString() === HTTP_UNAUTHORIZED) {
-          window.location.replace(LOGIN_URI);
-      }
-      return response;
-  }
+    handleError(response) {
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: Shall we go with two-space indentation for JS files?
JS and HTML files tend to have lot of inner elements. Four-space indentation makes it a bit harder to read.

@sameeraw @lasanthaDLPDS @vidurananayakkara wdyt?

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 10]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
+                    const subHeader = (<td style={{padding: 5}}>
+                        <i> {this.state.currentInfra.relatedProduct}/
+                            {this.state.currentInfra.relatedDeplymentPattern} /
+                            {this.state.currentInfra.infraParameters}</i>
+                    </td>);
+                    switch (this.state.currentInfra.testPlanStatus) {
+                        case FAIL:
+                            return <Subheader style={{
+                                fontSize: '20px',
+                                backgroundColor: "#ffd6d3"
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: Is it advisable set css styling info within the js files like this? What's the best practice for better maintainability of the code?

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 2 above)
Comment (kasunbg) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Let's raise a ticket and handle it elsewhere. We will have new set of statuses pretty soon as well.

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 11]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
+                                                            wordWrap: "break-word",
+                                                            whiteSpace: "wrap"
+                                                        }}>{data.totalFail}</td>
+                                                    <td
+                                                        style={{
+                                                            width: "15%",
+                                                            textAlign: "center",
+                                                            fontSize: "20px",
+                                                            wordWrap: "break-word",
+                                                            whiteSpace: "wrap"
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: hard-coded css within js files.

File: web/src/main/react-dashboard/src/components/TestRunView.js [hunk 12]
```diff
@@ -49,563 +42,570 @@ import {FAIL, SUCCESS, ERROR, PENDING, RUNNING, HTTP_UNAUTHORIZED, LOGIN_URI, TE
...
+                                                                        <td
+                                                                            style={{width: "5%"}}>
+                                                                            {entry.isTestSuccess ?
+                                                                                <img width="36"
+                                                                                     height="36"
+                                                                                     src={require('../success.png')}/>
+                                                                                :
+                                                                                <img width="36"
+                                                                                     height="36"
+                                                                                     src={require('../close.png')}/>}
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/TestRunView.js]: @lasanthaDLPDS As you see, four-space indentation tend to make the codes right-aligned. :) 
It's a bit harder to read as well.

File: web/src/main/react-dashboard/src/containers/ScenarioContainer.js [hunk 13]
```diff
@@ -19,12 +19,12 @@
...
+const mapStateToProps = (state, ownProps) => ({
+    active: state
+});
 
 const ScenarioContainer = connect(
     mapStateToProps
-)(ScenarioView)
+)(ScenarioView);
 
 export default ScenarioContainer;
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/containers/ScenarioContainer.js]: Missing new line.

Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/containers/ScenarioContainer.js]: Fixed with 5abab08

File: web/src/main/java/org/wso2/testgrid/web/api/ProductService.java (hunk 3 above)
Comment (lasanthaDLPDS) [reply web/src/main/java/org/wso2/testgrid/web/api/ProductService.java]: Fixed with 4be247e

File: web/src/main/java/org/wso2/testgrid/web/api/ProductService.java (hunk 4 above)
Comment (lasanthaDLPDS) [reply web/src/main/java/org/wso2/testgrid/web/api/ProductService.java]: Fixed with 4be247e

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 10 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: AFAIK inline CSS is not a good practice. Let's raise a ticket and handle these kind of things. WDYT?

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 11 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Shall we raise a separate ticket and handle this?

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 9 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: +1 Let's add two-space indentation for JS files.

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 8 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: This page will render when URL pattern matches to https://<host>:<port>/<product-ame>/<deployment-pattern-name>/test-plans/<testplan-id>.

Comment (kasunbg) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Ah ok..

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 9 above)
Comment (kasunbg) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Cool.. Can you change and re-send?

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 10 above)
Comment (kasunbg) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: +1

File: web/src/main/react-dashboard/src/components/ProductStatusView.js (hunk 5 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/ProductStatusView.js]: Fixed with 12488d2

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 7 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: +1 It is a better approach and lets raise a separate ticket and handle this as well.

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 12 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Fixed with 5c24430

File: web/src/main/react-dashboard/src/components/TestRunView.js (hunk 9 above)
Comment (lasanthaDLPDS) [reply web/src/main/react-dashboard/src/components/TestRunView.js]: Fixed with 5c24430
