### PR TITLE
Modify AWSArtifactReader to get AWS credentials from properties file

### LINKED ISSUE #409: Dashboard log view page does not load properly
**Description:**
Please note below at https://testgrid-live.private.wso2.com/testgrid/dashboard/testplans/9bf24413-4217-4915-b238-ba0c5800c447

image

The direct URL given above does not work though. You have to start from beginning!! :) Please fix that as part of this.

**Affected Product Version:**
0.9.0-m10

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

### LINKED ISSUE #410: Log download link does not work
**Description:**

This behavior can be see at: https://testgrid-live-dev.private.wso2.com/testgrid/dashboard/testplans/be52b8e9-af52-43d1-9d22-ee0ef6430f75

image

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
#409

### PR DESCRIPTION
**Pull request by azinneera**
## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java [hunk 1]
```diff
@@ -34,37 +37,29 @@
...
      *
      * @param region region where the S3 bucket is located
      * @param bucket name of the bucket
-     * @throws ArtifactReaderException thrown if the given parameters are null or empty or if
-     *                                 the {@value AWS_ACCESS_KEY} and {@value AWS_SECRET_KEY} environment variable
-     *                                 values are not set
+     * @throws ArtifactReaderException thrown if the given parameters are null or empty
      */
     public AWSArtifactReader(String region, String bucket) throws ArtifactReaderException {
-        String awsIdentity = System.getenv(AWS_ACCESS_KEY);
```
Comment (pasindujw) [inline web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java]: We could have use the existing configuration context to get values from property file as well. :)
`String awsIdentity = ConfigurationContext.getProperty(AWS_ACCESS_KEY_ID);`

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 2]
```diff
@@ -174,17 +174,17 @@ public Response getLogContent(@PathParam("id") String id, @QueryParam("truncate"
                                                                 artifactDownloadable.readArtifact(bucketKey);
             return Response.status(Response.Status.OK).entity(truncatedInputStreamData).build();
         } catch (TestGridDAOException e) {
-            String msg = "Error occurred while fetching the TestPlan by id : '" + id + "'";
+            String msg = "Error occurred while fetching the TestPlan by id : '" + id + "' " + e;
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: s/e/e.getMessage()/g
(substitue e with e.getMessage!)

File: web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java (hunk 1 above)
Comment (azinneera) [reply web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java]: PropertiesFileCredentialsProvider type of AWSCredentialsProvider takes the property file as an argument. Reading the file and extracting the property is handled by the PropertiesFileCredentialsProvider. It is not needed to extract the property value from the file. IMO, ConfigurationContext.getProperty is not necessary here. WDYT?

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java (hunk 2 above)
Comment (azinneera) [reply web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: Fixed in 2c5c954

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 3]
```diff
@@ -174,17 +174,17 @@ public Response getLogContent(@PathParam("id") String id, @QueryParam("truncate"
                                                                 artifactDownloadable.readArtifact(bucketKey);
             return Response.status(Response.Status.OK).entity(truncatedInputStreamData).build();
         } catch (TestGridDAOException e) {
-            String msg = "Error occurred while fetching the TestPlan by id : '" + id + "'";
+            String msg = "Error occurred while fetching the TestPlan by id : '" + id + "' " + e.getMessage();
```
Comment (vidurananayakkara) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: We are passing the message along with the exception when logging. Shall we append `e.getMessage()` when sending the response?

Comment (kasunbg) [reply web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: I don't think it would make much difference. Some people prefer to have the cause message in the first line itself.

File: web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java [hunk 4]
```diff
@@ -34,37 +38,32 @@
...
-        if (StringUtil.isStringNullOrEmpty(awsIdentity) || StringUtil.isStringNullOrEmpty(awsSecret)) {
-            throw new ArtifactReaderException("AWS Credentials must be set as environment variables");
-        }
         if (StringUtil.isStringNullOrEmpty(region)) {
             throw new ArtifactReaderException("AWS S3 bucket region is null or empty");
         }
         if (StringUtil.isStringNullOrEmpty(bucket)) {
             throw new ArtifactReaderException("AWS S3 bucket name is null or empty");
         }
+        Path configFilePath = Paths.get(TESTGRID_HOME, "testgrid-web-config.properties");
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java]: Please use the TestGridUtil to get the testgrid_home. This const does not exist anymore. :)
 
https://github.com/wso2/testgrid/pull/436/files#diff-6ba7f91913f30091dfafa23448132eb3L47

File: web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java (hunk 1 above)
Comment (pasindujw) [reply web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java]: Yes, true :+1:

File: web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java (hunk 4 above)
Comment (azinneera) [reply web/src/main/java/org/wso2/testgrid/web/plugins/AWSArtifactReader.java]: Fixed in 7178862
