### PR TITLE
Remove DeletionPolicy element at CF-script pre-process step

### LINKED ISSUE #423: Pre-process the Cloudformation RDS creation logic to remove "DeletionPolicy: snapshot"
**Description:**
If the deletion policy is set to snapshot, then, AWS makes a backup of the database before deletion. But, AWS has a limitation on how many manual snapshots we can create (100). 

Since testgrid re-spawns CF stacks again and again, we need to remove this policy. This may be specific to TestGrid, therefore pre-processing of the cf script is needed.

This can be found here:
https://github.com/wso2/cloudformation-is/blob/master/cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml#L501

Error on AWS side is this:

image

**Affected Product Version:**
0.9.0-m10

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
See above.

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by pasindujw**
**Purpose**
If the deletion policy is set to snapshot, then, AWS makes a backup of the database before deletion. But, AWS has a limitation on how many manual snapshots we can create (100).
Since testgrid re-spawns CF stacks again and again, we need to remove this policy. 
Fixes #423 

**Approach**
Check for the DeletionPolicy element at the CF script pre-process stage and remove it.

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java [hunk 1]
```diff
@@ -54,15 +61,39 @@ private static String appendRandomValue(String key, String script) {
...
                         StringUtil.generateRandomString(RANDOMIZED_STR_LENGTH);
             }
             newScript.append(line).append(System.lineSeparator());
         }
         return newScript.toString();
     }
+
+    /**
+     * This method removes the elements which contains the key passed.
+     * @param key Key of the element which should be removed.
```
Comment (azinneera) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/CloudFormationScriptPreprocessor.java]: New line expected
