### PR TITLE
Fix undefined error when loading test log view

### LINKED ISSUE #382: Fix undefined error when navigating to test log view in web app
**Description:**
When navigating to the web app the following error is displayed.

```
react-dom.production.min.js:164 TypeError: Cannot read property 'infraParameters' of undefined
    at t.value (TestRunView.js:116)
    at l (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at o (react-dom.production.min.js:161)
    at s (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:162)
    at C (react-dom.production.min.js:169)
    at w (react-dom.production.min.js:168)
    at p (react-dom.production.min.js:167)
    at f (react-dom.production.min.js:165)
l @ react-dom.production.min.js:164
TestRunView.js:116 Uncaught (in promise) TypeError: Cannot read property 'infraParameters' of undefined
    at t.value (TestRunView.js:116)
    at l (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at o (react-dom.production.min.js:161)
    at s (react-dom.production.min.js:161)
    at a (react-dom.production.min.js:162)
    at C (react-dom.production.min.js:169)
    at w (react-dom.production.min.js:168)
    at p (react-dom.production.min.js:167)
    at f (react-dom.production.min.js:165)
Failed to load resource: the server responded with a status of 404 ()
```

### PR DESCRIPTION
**Pull request by vidurananayakkara**
## Purpose
Resolves #382
Fix undefined error when navigating to test log view in web app

## Release note
* Fixed undefined error when navigating to test log view in web app

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Related PRs
* https://github.com/wso2/testgrid/pull/360

### CODE REVIEW

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 1]
```diff
@@ -176,17 +176,17 @@ public Response getLogContent(@PathParam("id") String id, @QueryParam("truncate"
         } catch (TestGridDAOException e) {
             String msg = "Error occurred while fetching the TestPlan by id : '" + id + "'";
             logger.error(msg, e);
-            return Response.serverError()
+            return Response.serverError().status(Response.Status.INTERNAL_SERVER_ERROR)
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: Both #serverError, or set the status code to 500 does the same thing. [1] I'm not sure why we need to do the same thing twice!

http://grepcode.com/file/repo1.maven.org/maven2/javax.ws.rs/jsr311-api/1.0/javax/ws/rs/core/Response.java#199

File: web/src/main/react-dashboard/src/components/DeploymentPatternView.js [hunk 2]
```diff
@@ -97,6 +97,8 @@ class DeploymentPatternView extends Component {
                         <TableRowColumn>
                           <FlatButton style={{color: '#0E457C'}}
                                       onClick={() => this.navigateToRoute("/testgrid/v0.9/testplans/" + value.lastBuild.id, {
+                                        deploymentName: key
```
Comment (kasunbg) [inline web/src/main/react-dashboard/src/components/DeploymentPatternView.js]: *deploymentPatternName
