### PR TITLE
Fix dashboard issues

### LINKED ISSUE #391: The admin portal URL in dashboard is not correct
**Description:**
$subject. See the image:

image

**Affected Product Version:**
0.9.0-m9

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

### LINKED ISSUE #395: TestGrid dashboard API fails when database returns empty resultsets.
**Description:**
When there are zero results for the database queries, API returns status code 500

**Suggested Labels:**
Type/Bug
Severity/Critical
Priority/Highest

**Suggested Assignees:**
Sameera Wickramasekara

**Affected Product Version:**
0.9.0-m9

### PR DESCRIPTION
**Pull request by sameerawickramasekara**
## Purpose
Resolves #395 
Resolves #391

## Goals
Fix dashboard issues that arise when the database results are empty for queries
Fix broken admin URL

## Approach
API returns null value when there are no records and dashboard handles those null values appropriately

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: web/src/main/react-dashboard/src/components/DeploymentPatternView.js [hunk 1]
```diff
@@ -43,7 +43,7 @@ class DeploymentPatternView extends Component {
   }
 
   componentDidMount() {
-     var url = '/testgrid/v0.9/api/test-plans/product/' + this.props.active.reducer.currentProduct.productId;
+    var url = '/testgrid/v0.9/api/test-plans/product/' + this.props.active.reducer.currentProduct.productId;
```
Comment (vidurananayakkara) [inline web/src/main/react-dashboard/src/components/DeploymentPatternView.js]: Since this value is not changed we can make this a constant. WDYT?

File: web/src/main/react-dashboard/src/App.js [hunk 2]
```diff
@@ -80,7 +80,7 @@ class App extends Component {
                 backgroundColor: '#424242',position: 'fixed'}}
                 iconElementLeft={<IconButton onClick={this.handleClose}>{this.state.open ? <NavigationBack /> : <NevigationExpand />}</IconButton>}> </AppBar>
               <Drawer open={this.state.open} containerStyle={{ 'top': '64px', backgroundColor:'#BDBDBD'}} width={200} >
-                <MenuItem><a href="https://testgrid-live.private.wso2.com/jenkins/blue/organizations/jenkins/wso2is-5.4.0%2F01-single-node-deployment-pattern/"> TestGrid AdminPortal</a></MenuItem>
+                <MenuItem><a href="/blue/organizations/jenkins/wso2is5.4.0LTS/activity"> TestGrid AdminPortal</a></MenuItem>
```
Comment (vidurananayakkara) [inline web/src/main/react-dashboard/src/App.js]: What is the possibility of generating this link on the fly?

File: web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java [hunk 3]
```diff
@@ -72,16 +74,18 @@ static Product getProductBean(org.wso2.testgrid.common.Product product) {
...
      * @return {@link DeploymentPattern} instance with necessary information
      */
     static DeploymentPattern getDeploymentPatternBean(org.wso2.testgrid.common.DeploymentPattern deploymentPattern,
                                                       String status) {
         DeploymentPattern deploymentPattern1 = new DeploymentPattern();
-        deploymentPattern1.setId(deploymentPattern.getId());
-        deploymentPattern1.setName(deploymentPattern.getName());
-        deploymentPattern1.setProductId(deploymentPattern.getProduct().getId());
-        deploymentPattern1.setTestStatus(status);
+        if (deploymentPattern != null) {
```
Comment (vidurananayakkara) [inline web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java]: Shall we change the variable names `deploymentPattern` and `deploymentPattern1` to something more meaningful since it is hard to distinguish which one is which at the moment

File: web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java [hunk 4]
```diff
@@ -117,21 +121,23 @@ static DeploymentPattern getDeploymentPatternBean(org.wso2.testgrid.common.Deplo
...
-        testPlan1.setDeploymentPattern(testPlan.getDeploymentPattern().getName());
-        testPlan1.setDeploymentPatternId(testPlan.getDeploymentPattern().getId());
-        testPlan1.setInfraParams(testPlan.getInfraParameters());
-        testPlan1.setStatus(testPlan.getStatus().toString());
-        testPlan1.setCreatedTimestamp(testPlan.getCreatedTimestamp());
-        testPlan1.setModifiedTimestamp(testPlan.getModifiedTimestamp());
-        if (requireTestScenarios) {
-            testPlan1.setTestScenarios(getTestScenarioBeans(testPlan.getTestScenarios(), false));
+        if (testPlan != null) {
+            testPlan1.setId(testPlan.getId());
```
Comment (vidurananayakkara) [inline web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java]: Shall we change the variable names `testPlan` and `testPlan1` to something more meaningful since it is hard to distinguish which one is which at the moment

File: web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java [hunk 5]
```diff
@@ -157,18 +163,20 @@ static TestPlan getTestPlanBean(org.wso2.testgrid.common.TestPlan testPlan, bool
...
     static TestScenario getTestScenarioBean(org.wso2.testgrid.common.TestScenario testScenario,
                                             boolean requireTestCases) {
         TestScenario testScenario1 = new TestScenario();
-        testScenario1.setId(testScenario.getId());
-        testScenario1.setName(testScenario.getName());
-        testScenario1.setStatus(testScenario.getStatus().toString());
-        if (requireTestCases) {
-            testScenario1.setTestCases(getTestCaseBeans(testScenario.getTestCases()));
+        if (testScenario != null) {
+            testScenario1.setId(testScenario.getId());
```
Comment (vidurananayakkara) [inline web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java]: Shall we change the variable names `testScenario` and `testScenario1` to something more meaningful since it is hard to distinguish which one is which at the moment

File: web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java [hunk 6]
```diff
@@ -199,12 +207,14 @@ static TestScenario getTestScenarioBean(org.wso2.testgrid.common.TestScenario te
...
     static TestCase getTestCaseBean(org.wso2.testgrid.common.TestCase testCase) {
         TestCase testCase1 = new TestCase();
-        testCase1.setId(testCase.getId());
-        testCase1.setName(testCase.getName());
-        testCase1.setSuccess(testCase.isSuccess());
-        testCase1.setModifiedTimestamp(testCase.getModifiedTimestamp());
-        testCase1.setCreatedTimestamp(testCase.getCreatedTimestamp());
-        testCase1.setErrorMsg(testCase.getFailureMessage());
+        if (testCase != null) {
+            testCase1.setId(testCase.getId());
```
Comment (vidurananayakkara) [inline web/src/main/java/org/wso2/testgrid/web/api/APIUtil.java]: Shall we change the variable names `testCase` and `testCase1` to something more meaningful since it is hard to distinguish which one is which at the moment

File: web/src/main/react-dashboard/src/App.js (hunk 2 above)
Comment (sameerawickramasekara) [reply web/src/main/react-dashboard/src/App.js]: created issue #400 to track this issue in next milestones
