### PR TITLE
Option to persist test scenario results in S3 and download per-scenario

### LINKED ISSUE #795: Persist scenario test results/artifacts in S3 in correct build directory.
**Description:**
Currently JTL files and scenario test logs are uploaded to S3 as the same directory they were created in the workplace.
(ex:   <Product Name>/workspace/identity-test-integration/scenarios/scenario01/jmeter/ xxxxx.jtl )
But those has to be persist in the relevant build directory of the product.
readme - testgrid s3 structure revealed

Addition to that, the artifacts will needed to be in zipped format also in case a user need to download them.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
m30
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by pasindujw**
**Purpose**
Fixes #795 
Now the logs are persisted in S3 as below;

readme - testgrid s3 structure revealed

The user is also able to download per-scenario results as below;
result

**Security checks**
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 1]
```diff
@@ -394,4 +401,71 @@ private TestExecutionSummary getTestExecutionSummary(TestPlan testPlan) {
...
+
+    /**
+     * Returns the result (archive file) to the given scenario of a test plan.
+     *
+     * @param id test plan id
+     * @param scenarioDir scenario directory name
+     * @return archived file of the results
+     */
+    @GET
+    @Path("/result/{id}/{scenarioDir}")
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: Shall we say 'test-plan-id' to make it more meaningful? Then we don't have to look at the javadoc.. :)

Comment (kasunbg) [reply web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: What is the scenarioDir?? If this is a jargon we are going to use, we should document this somewhere.

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 2]
```diff
@@ -394,4 +401,71 @@ private TestExecutionSummary getTestExecutionSummary(TestPlan testPlan) {
...
+                return Response
+                        .ok(artifactDownloadable.getArtifactStream(bucketKey))
+                        .type(RESPONSE_HEADER_VALUE_APPLICATION_ZIP)
+                        .header(RESPONSE_HEADER_CONTENT_DISPOSITION, RESPONSE_HEADER_VALUE_ATTACHMENT + "; " +
+                                RESPONSE_HEADER_FILE_NAME + "=\" " + scenarioDir +
+                                TESTGRID_COMPRESSED_FILE_EXT + "\"")
+                        .build();
+            } else {
+                return Response.status(Response.Status.NOT_FOUND)
+                        .entity("Couldn't found result-artifacts in the remote location").build();
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: At the same time, we should log an error to testgrid.log mentioning this error condition. 
The log should have more context - things like product name, test-plan-id, scenario-id, the s3 result-artifacts location you were trying, etc.

File: web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java [hunk 3]
```diff
@@ -394,4 +401,71 @@ private TestExecutionSummary getTestExecutionSummary(TestPlan testPlan) {
...
+            }
+        } catch (TestGridDAOException e) {
+            String msg = "Error occurred while fetching the TestPlan by id : '" + id + "' ";
```
Comment (kasunbg) [inline web/src/main/java/org/wso2/testgrid/web/api/TestPlanService.java]: Just the 'id' enough to debug this error when all you have is the log file without access to the testgrid runtime/s3 etc.? From product support perspective, that's all we have usually.
