### PR TITLE
Fix exit status of TestGrid

### LINKED ISSUE #321: TestGrid test-run Jenkinsfile contains bad code
**Description:**

The shell script execution in TestGrid jenkins fails always no matter what the return status of the java command in there. [1] 

Because of this, we have added try-catch block and set 'success' in both blocks. This is a major issue, so we have to fix this. 

[1] https://github.com/wso2-incubator/testgrid/blob/master/jenkins-pipelines/Jenkinsfile#L74

**Steps to reproduce:**
This can be seen here:
image

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by sameerawickramasekara**
## Purpose
Resolves #321 

## Goals
TestGrid jar exit code was 1 in every execution. this was caused by unexpected exception occurring while waiting for infrastructure destroying.

## Approach
Used classes provided by the aws-java-sdk to wait for the aws related tasks .

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: common/src/main/java/org/wso2/testgrid/common/Script.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public String toString() {
     }
 
     public Properties getScriptParameters() {
-        return scriptParameters;
+        return scriptParameters != null ? scriptParameters : new Properties();
```
Comment (kasunbg) [inline common/src/main/java/org/wso2/testgrid/common/Script.java]: Shall we initialize the scriptParameters with a Properties instance? Otherwise, each get will create a new Properties instance unnecessarily.

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java [hunk 2]
```diff
@@ -47,17 +48,22 @@ public String getDeployerName() {
...
-        logger.info("Deploying the pattern..");
-        DeploymentValidator validator = new DeploymentValidator();
-        logger.info("Waiting for server startup..");
-        for (Host host : deployment.getHosts()) {
-            try {
-                new URL(host.getIp());
-            } catch (MalformedURLException e) {
-                continue;
+        try {
+            logger.info("Deploying the pattern..");
```
Comment (kasunbg) [inline deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: What pattern?

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java [hunk 3]
```diff
@@ -47,17 +48,22 @@ public String getDeployerName() {
...
+            DeploymentValidator validator = new DeploymentValidator();
+            logger.info("Waiting for server startup..");
+            for (Host host : deployment.getHosts()) {
+                try {
+                    new URL(host.getIp());
+                } catch (MalformedURLException e) {
+                    continue;
```
Comment (kasunbg) [inline deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: If the URL is malformed, 'continue' will cause a busy-loop. Shouldn't we throw the exception and stop the entire process?

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java [hunk 4]
```diff
@@ -47,17 +48,22 @@ public String getDeployerName() {
...
+                }
+                validator.waitForDeployment(host.getIp(), 60, TimeUnit.MINUTES, 15, TimeUnit.SECONDS);
             }
-            validator.waitForDeployment(host.getIp(), 60, TimeUnit.MINUTES, 15, TimeUnit.SECONDS);
+        } catch (ConditionTimeoutException ex) {
+            throw new TestGridDeployerException("Time out while waiting for deployment", ex);
```
Comment (kasunbg) [inline deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: How long is the timeout?

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java [hunk 5]
```diff
@@ -47,17 +48,22 @@ public String getDeployerName() {
...
+            logger.info("Deploying the pattern..");
+            DeploymentValidator validator = new DeploymentValidator();
+            logger.info("Waiting for server startup..");
+            for (Host host : deployment.getHosts()) {
+                try {
+                    new URL(host.getIp());
+                } catch (MalformedURLException e) {
+                    continue;
+                }
+                validator.waitForDeployment(host.getIp(), 60, TimeUnit.MINUTES, 15, TimeUnit.SECONDS);
```
Comment (kasunbg) [inline deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: Please make the timeout value a constant.

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java [hunk 6]
```diff
@@ -118,9 +121,14 @@ public Deployment createInfrastructure(Script script, String infraRepoDir) throw
...
             if (logger.isDebugEnabled()) {
-                logger.info("Stack configuration created for name " + cloudFormationName);
+                logger.info(StringUtil.concatStrings("Stack configuration created for name ", cloudFormationName));
             }
-            waitForAWSProcess(stackbuilder, cloudFormationName);
+            logger.info(StringUtil.concatStrings("Waiting for stack : ", cloudFormationName));
+            Waiter<DescribeStacksRequest> describeStacksRequestWaiter = new AmazonCloudFormationWaiters(stackbuilder)
+                    .stackCreateComplete();
+            describeStacksRequestWaiter.run(new WaiterParameters<>(new DescribeStacksRequest()));
+            logger.info(StringUtil.concatStrings("Stack : ", cloudFormationName, " creation complete!"));
```
Comment (kasunbg) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java]: *completed.

File: infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java [hunk 7]
```diff
@@ -146,64 +154,14 @@ public Deployment createInfrastructure(Script script, String infraRepoDir) throw
             Deployment deployment = new Deployment();
             deployment.setHosts(hosts);
             return deployment;
-        } catch (InterruptedException e) {
-            throw new TestGridInfrastructureException("Error occured while waiting for " +
-                    "CloudFormation Stack creation", e);
+        } catch (WaiterUnrecoverableException e) {
+            throw new TestGridInfrastructureException(StringUtil.concatStrings("Error while waiting for stack : "
+                    , cloudFormationName, "to complete"), e);
```
Comment (kasunbg) [inline infrastructure/src/main/java/org/wso2/testgrid/infrastructure/aws/AWSManager.java]: *" to complete" (missing space.)

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java (hunk 3 above)
Comment (sameerawickramasekara) [reply deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: In this code, the correct output URLs to wait upon are identified by this method.
all other values are skipped by the MalformedURLException

Comment (kasunbg) [reply deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: Got it.. Shall we log that as an error then?

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java [hunk 8]
```diff
@@ -58,10 +63,11 @@ public Deployment deploy(Deployment deployment) throws TestGridDeployerException
                 } catch (MalformedURLException e) {
                     continue;
                 }
-                validator.waitForDeployment(host.getIp(), 60, TimeUnit.MINUTES, 15, TimeUnit.SECONDS);
+                validator.waitForDeployment(host.getIp(), TIMEOUT, TIMEOUT_UNIT, POLL_INTERVAL, POLL_UNIT);
```
Comment (kasunbg) [inline deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: We should wait on a port of a given IP/host, not the IP itself.

File: deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java (hunk 3 above)
Comment (sameerawickramasekara) [reply deployment/src/main/java/org/wso2/testgrid/deployment/deployers/AWSDeployer.java]: Done
