### PR TITLE
Fix failure in persistence of concurrent scenario samplers

### LINKED ISSUE #424: When scenario samplers are executing concurrently DB persistence fails
**Description:**

If Test scenario samplers are executing parallel the DB updating fails with the following error.

```
ERROR {} Detected problem in Listener. java.lang.RuntimeException: Error occurred when persisting test case.
	at org.wso2.testgrid.automation.executor.JMeterResultCollector.sampleOccurred(JMeterResultCollector.java:69)
	at org.apache.jmeter.threads.ListenerNotifier.notifyListeners(ListenerNotifier.java:65)
	at org.apache.jmeter.threads.JMeterThread.notifyListeners(JMeterThread.java:891)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:528)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:424)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:255)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.testgrid.dao.TestGridDAOException: Error occurred when persisting entity in database.
	at org.wso2.testgrid.dao.repository.AbstractRepository.persist(AbstractRepository.java:73)
	at org.wso2.testgrid.dao.repository.TestCaseRepository.persist(TestCaseRepository.java:53)
	at org.wso2.testgrid.dao.uow.TestCaseUOW.persistTestCase(TestCaseUOW.java:69)
	at org.wso2.testgrid.automation.executor.JMeterResultCollector.sampleOccurred(JMeterResultCollector.java:67)
	... 6 more
Caused by: java.lang.IllegalStateException: 
Exception Description: Transaction is currently active
	at org.eclipse.persistence.internal.jpa.transaction.EntityTransactionImpl.begin(EntityTransactionImpl.java:45)
	at org.wso2.testgrid.dao.repository.AbstractRepository.persist(AbstractRepository.java:65)
	... 9 more
```

**Suggested Labels:**
Bug

### PR DESCRIPTION
**Pull request by azinneera**
## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java [hunk 1]
```diff
@@ -92,7 +94,7 @@ public void execute(String script, Deployment deployment) throws TestAutomationE
             throw new TestAutomationException(StringUtil.concatStrings("Script file ", script, " cannot be located."));
         }
 
-        ResultCollector resultCollector = new JMeterResultCollector(summariser, testScenario);
+        JMeterResultCollector resultCollector = new JMeterResultCollector(summariser, testScenario);
```
Comment (vidurananayakkara) [inline automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java]: We can set the test cases to the testScenario and persist testScenario directly. This will persist all the test cases. However please do check if we are getting a null pointer exception stating that the entity ID is null.

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java [hunk 2]
```diff
@@ -73,13 +74,20 @@ public void sampleOccurred(SampleEvent sampleEvent) {
                                             result.getResponseMessage().replaceAll("\"", "\\\""),
                                             "\", \"Sampler Data\": \"",
                                             samplerData.replaceAll("\"", "\\\""), "\"}");
-            // Persist result to the database
-            testCaseUOW.persistTestCase(result.getSampleLabel(), testScenario, result.isSuccessful(), failureMessage);
+            // Add result to concurrent list
+            TestCase testCase = new TestCase();
```
Comment (vidurananayakkara) [inline automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java]: As stated in the above comment, we can set the test cases directly in the test scenario. We might need to use a `CopyOnWriteArrayList` in the test scenario

File: dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java [hunk 3]
```diff
@@ -47,25 +47,10 @@ public TestCaseUOW() {
...
-                                    String responseMessage) throws TestGridDAOException {
-        // Create test case instance
-        TestCase testCase = new TestCase();
-        testCase.setName(testName);
-        testCase.setSuccess(isSuccess);
-        testCase.setTestScenario(testScenario);
-        testCase.setFailureMessage(responseMessage);
-
-        // Set test scenario -> test case link
-        testScenario.addTestCase(testCase);
```
Comment (kasunbg) [inline dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java]: We need this logic in your new design as well. Please add.

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java [hunk 4]
```diff
@@ -73,13 +74,20 @@ public void sampleOccurred(SampleEvent sampleEvent) {
...
             jmeterResultLogger.info(StringUtil.concatStrings("Test case :", result.getSampleLabel(),
                     " failed for scenario: ", testScenario.getName(), "\n", failureMessage, "\", \"Sampler Data\": \"",
                     result.getSamplerData().replaceAll("\"", "\\\""), "\"}"));
-        } catch (TestGridDAOException e) {
-            throw new RuntimeException(StringUtil.concatStrings("Error occurred when persisting test case."), e);
-        }
+
+    }
+
+    public List<TestCase> getTestCases() {
```
Comment (kasunbg) [inline automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java]: This returns the list of testcases that has been executed, right? I mean, it won't list unless the test case has come into the `sampleOccurred` method, isn't it? I think we should document that.

Further, we need another boolean flag that specify whether all the test cases of a given scenario are ran or not. We don't need to do this part in this PR. Please raise a separate ticket.

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java (hunk 1 above)
Comment (kasunbg) [reply automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java]: +1. Not required for this PR. Please raise a ticket.

File: dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java (hunk 3 above)
Comment (azinneera) [reply dao/src/main/java/org/wso2/testgrid/dao/uow/TestCaseUOW.java]: Added in e54bcc6

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java (hunk 4 above)
Comment (azinneera) [reply automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java]: > This returns the list of testcases that has been executed, right? I mean, it won't list unless the test case has come into the sampleOccurred method, isn't it?

Correct.
> Please raise a separate ticket.

Raised #467

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java (hunk 1 above)
Comment (azinneera) [reply automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterExecutor.java]: Raised #474

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java (hunk 2 above)
Comment (azinneera) [reply automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java]: This would be resolved in #474

File: automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java (hunk 4 above)
Comment (azinneera) [reply automation/src/main/java/org/wso2/testgrid/automation/executor/JMeterResultCollector.java]: Added a javadoc comment explaining the method in e59c4e3
