### PR TITLE
Gracefully handle failures in each step of product deployment verification.

### LINKED ISSUE #494: Call infra_destroy scripts irrespective of any failure in intermediate steps
**Description:**
It is important to call infra_destroy and cleanup the resources after provisioning the infrastructure. This call should happen irrespective of any failure while executing intermediate steps such as deployment/scenario failure.

Today, I noticed that a NPE was thrown from _automation_ package. Because of this, testgrid has shutdown, hence the infra_destroy step never executed.

```log
[2018-02-16 00:10:22,835]  INFO {org.wso2.testgrid.core.ScenarioExecutor} - Executing Tests for Solution Pattern : scenario01
[2018-02-16 00:10:22,865]  INFO {org.wso2.testgrid.core.ScenarioExecutor} - Executing scenario01 Test
[2018-02-16 00:10:22,898]  WARN {org.apache.jmeter.util.JMeterUtils} - Exception 'null' occurred when fetching boolean property:'server.exitaftertest', defaulting to:false
[2018-02-16 00:10:22,898]  WARN {org.apache.jmeter.util.JMeterUtils} - Exception 'null' occurred when fetching boolean property:'jmeterengine.remote.system.exit', defaulting to:false
[2018-02-16 00:10:22,898]  WARN {org.apache.jmeter.util.JMeterUtils} - Exception 'null' occurred when fetching boolean property:'jmeterengine.stopfail.system.exit', defaulting to:true
[2018-02-16 00:10:22,898]  WARN {org.apache.jmeter.util.JMeterUtils} - Exception 'null' occurred when fetching boolean property:'jmeterengine.force.system.exit', defaulting to:false
[2018-02-16 00:10:22,899]  INFO {org.wso2.testgrid.automation.executor.JMeterExecutor} - JMeter user.properties file not specified - proceeding with JMeter default properties.
Exception in thread "main" java.lang.NullPointerException
	at org.wso2.testgrid.automation.executor.JMeterExecutor.replaceProperties(JMeterExecutor.java:220)
	at org.wso2.testgrid.automation.executor.JMeterExecutor.execute(JMeterExecutor.java:72)
	at org.wso2.testgrid.automation.Test.execute(Test.java:149)
	at org.wso2.testgrid.core.ScenarioExecutor.runScenario(ScenarioExecutor.java:83)
	at org.wso2.testgrid.core.TestPlanExecutor.runTestPlan(TestPlanExecutor.java:72)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.executeTestPlan(RunTestPlanCommand.java:273)
	at org.wso2.testgrid.core.command.RunTestPlanCommand.execute(RunTestPlanCommand.java:133)
	at org.wso2.testgrid.core.command.CommandHandler.execute(CommandHandler.java:119)
	at org.wso2.testgrid.core.Main.main(Main.java:49)
```

**Affected Product Version:**
0.9.0-m13

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
We can easily re-produce this by adding a `throw NPE` clause to JMeterExecutor#execute method.

**Related Issues:**
N/A

### LINKED ISSUE #515: Gracefully handle failures that happen during infra provisioning
**Description:**
ATM, a NPE thrown in [#provisionInfrastructure](https://github.com/wso2/testgrid/blob/1ebec184750a8d4e928291f317a0185195ed0240/core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java#L134) method [1] can break the entire flow of the _run-testplan_ execution. That is not correct since we need to be able to _gracefully close any opened resources_ during infra provisioning and deployment creation.

This is especially true when provisioning infrastructure on AWS. Suppose the provisioned succeeded but the #provisionInfrastructure method threw an exception for another reason. In that case, the provisioned Cloudformation stack will be orphaned until someone manually cleans it.

Therefore, we need to introduce $subject.

**Affected Product Version:**
0.9.0-m14

**OS, DB, other environment details and versions:**    
cloudformation-is

**Steps to reproduce:**
Deliberately throw a runtime exception from the aforementioned method.

**Related Issues:**
#494

### PR DESCRIPTION
**Pull request by kasunbg**
## Purpose
Gracefully handle failures in each step of product deployment verification.

Fixes #515
Fixes #494

## Goals
The deployment shutdown and infrastructure release need to run in spite of failures during deployment creation nor infrastructure provisioning. Ideally, we want to make each of these steps as atomic as possible.

Further, any checked / un-checked exception thrown during a given scenario test run must not interfere the rest of the scenario test runs.

## Automation tests
 - Unit tests 
yes.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java [hunk 1]
```diff
@@ -152,37 +193,50 @@ private InfrastructureProvisionResult provisionInfrastructure(InfrastructureConf
...
             setTestPlanStatus(testPlan, Status.FAIL);
-            throw new TestPlanExecutorException(StringUtil
+            String msg = StringUtil
                     .concatStrings("No Infrastructure Provider implementation for deployment pattern '",
-                            testPlan.getDeploymentPattern(), "', in TestPlan"), e);
+                            testPlan.getDeploymentPattern(), "', in TestPlan");
+            logger.error(msg, e);
+        } catch (Exception e) {
+            // We need to catch the Exception here since we need to catch and handle all exceptions within this method.
+            // This is required to do gracefully close any opened resources. Created wso2/testgrid#515 to track.
```
Comment (pasindujw) [inline core/src/main/java/org/wso2/testgrid/core/TestPlanExecutor.java]: I think we can remove this comment, as it is the issue being addressed by this PR :)

File: core/src/test/resources/workspace/deployment/deploy.sh [hunk 2]
```diff
@@ -1,4 +1,33 @@
...
+done
+
+INFRA=$WORKSPACE/my-infrastructure
+if [ ! -d $INFRA ]; then
+  echo 'Cannot proceed the deployment. infrastructure dir is empty: ' ${INFRA}
+  exit 1;
+fi
+
+echo "Deploy server1" > $INFRA/my-deployment.txt
+cat $INFRA/my-deployment.txt
```
Comment (pasindujw) [inline core/src/test/resources/workspace/deployment/deploy.sh]: missing new line.
